services:
  gatsby_base: &gatsby_base
    image: syntapynew/gatsby_server
    tty: true
    stdin_open: true
    entrypoint: ["npm"]
    volumes:
      - type: bind
        source: "./gatsby"
        target: "/home/node/site"
    networks:
      - shared
    healthcheck:
      interval: 20s
      timeout: 5s
      retries: 3

  gatsby_dev:
    <<: *gatsby_base
    command: ["run", "develope"]
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
  gatsby_serve:
    <<: *gatsby_base
    command: ["run", "build:serve"]
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]

  e2e_client:
    image: syntapynew/cypress_client
    tty: true
    stdin_open: true
    entrypoint: ["npm"]
    depends_on:
      gatsby_serve:
        condition: service_healthy
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - type: bind
        source: "./cypress"
        target: "/home/node/site"
    networks:
      - shared

networks:
  shared:
    driver: bridge
