services:
  page:
    image: superformula/clone
    entrypoint:
      - npm
      - run
      - serve
    network_mode: "host"
    volumes:
      - type: bind
        source: "./gatsby"
        target: "/site"
