services:
  gatsby:
    image: gatsby_server
    tty: true
    stdin_open: true
    command: ["npm", "run", "develop"]
    volumes:
      - type: bind
        source: "./gatsby"
        target: "/site"
    networks:
      - shared
    ports:
      - "8000:8000"
  e2e_client:
    image: cypress_client
    tty: true
    stdin_open: true
    command: ["npm", "run", "e2e"]
    depends_on:
      - gatsby
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - type: bind
        source: "./gatsby"
        target: "/site"
    networks:
      - shared

networks:
  shared:
    driver: bridge
