services:
  page:
    image: superformula/clone
    entrypoint: [ 
     "sh", "-c", "npm install && npm run develop"
    ]
    network_mode: "host"
    volumes:
      - type: bind
        source: "./gatsby"
        target: "/site"
