services:
  page:
    image: superformula/clone
    volumes:
      - type: bind
        source: ./gatsby
        target: /page
    entrypoint:
      - npm
      - run
      - which
    network_mode: "host"
