services:
  gatsby:
    image: syntapynew/gatsby_server
    environment:
      CONTENTFUL_SPACE_ID: $CONTENTFUL_SPACE_ID
      CONTENTFUL_ACCESS_TOKEN: $CONTENTFUL_ACCESS_TOKEN
    tty: true
    stdin_open: true
    command: ["npm", "ci", ";", "npm", "run", "develop"]
    volumes:
      - type: bind
        source: "./gatsby"
        target: "/home/node/site"
    networks:
      - shared
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 20s
      timeout: 5s
      retries: 3
  e2e_client:
    image: syntapynew/cypress_client
    tty: true
    stdin_open: true
    entrypoint: ["cypress"]
    command: ["run", "--e2e", "--browser", "firefox", "--spec", "'cypress/e2e/**/*.cy.js'"]
    depends_on:
      - gatsby
    environment:
      - UID=${UID}
      - GID=${GID}
      - DISPLAY=${DISPLAY}
      - CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE_ID}
      - CONTENTFUL_ACCESS_TOKEN=${CONTENTFUL_ACCESS_TOKEN}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - type: bind
        source: "./cypress"
        target: "/home/node/site"
    networks:
      - shared

networks:
  shared:
    driver: bridge
