services:
  page:
    image: superformula/clone
    tty: true
    stdin_open: true
    entrypoint: [ 
      "bash"
    ]
    network_mode: "host"
    volumes:
      - type: bind
        source: "./gatsby"
        target: "/site"
