services:
  gatsby:
    image: syntapynew/gatsby_server
    environment:
      UID: $(id -u)
      GID: $(id -g)
    user: "${UID}:${GID}"
    tty: true
    stdin_open: true
    command: ["npm", "run", "develop"]
    volumes:
      - type: bind
        source: "./gatsby"
        target: "/site"
    networks:
      - shared
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 20s
      timeout: 5s
      retries: 3
  e2e_client:
    image: syntapynew/cypress_client
    tty: true
    stdin_open: true
    command: ["npm", "run", "e2e"]
    depends_on:
      - gatsby
    environment:
      UID: $(id -u)
      GID: $(id -g)
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - type: bind
        source: "./gatsby"
        target: "/site"
    networks:
      - shared

networks:
  shared:
    driver: bridge
