arg NODE_VERSION='22.9.0'

### Get versions from:
### 	https://hub.docker.com/r/cypress/factory/
arg CHROME_VERSION='129.0.6668.70-1'
arg EDGE_VERSION='129.0.2792.52-1'
arg FIREFOX_VERSION='130.0.1'

arg CYPRESS_VERSION='13.14.2'

from cypress/factory

run mkdir /site
workdir /site

run apt-get update && apt-get upgrade -y && \
        apt install -y x11-apps feh && \
        npm install cypress --save-dev && \
        npx cypress install
