from node:22-bookworm

env UID=1000
env GID=1000

run mkdir /home/node/site
workdir /home/node/site

run apt-get update && apt-get upgrade -y && \
    apt install -y net-tools && \
    npm install -g npm@latest && \
    npm install -g gatsby-cli

user node

volume /home/node/site

expose 8000/tcp
