name: docker

permissions: read-all
on: [push]
jobs:
  TestRunDocker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout out ${{ env.GITHUB_REF }}
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build container image
        run: ./bin/build-ci
      - name: npm run serve
        run: ./bin/run-ci
      - name: ifconfig
        run: ifconfig
      - name: ping localhost
        run: ping -c 5 localhost
      - name: ping server
        run: ping -c 5 localhost:8000
          #      - name: ping server
          #        uses: BerniWittmann/background-server-action@v1
          #        with:
          #command: ping -c 10 http://localhost:8000
          #          command: ifconfig
          #          start: ./bin/run-ci
          #          wait-on: 'http://localhost:8000'
            #      - name: run container
            #        run: ./bin/run-ci
            #      - name: ping container
            #        run: ping -c 5 localhost:8000
