name: docker

permissions: read-all

jobs:
  build_and_run:
    runs_on: ubuntu-latest
    steps:
      - name: checkout out ${{ env.GITHUB_REF }}
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build container image
        run: docker build -t superformula/clone .
      - name: run container
        run: docker compose up
      - name: ping container
        run: ping -c 5 localhost:8000
