name: cypress

permissions: read-all
on: [push]

env:
  NODE_VERSION: 22
  DISPLAY: ""
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: checkout ${{ env.GITHUB_REF }}
        uses: actions/checkout@v3
      - run: env
      - run: echo "NGID=$(id -g)" >> $GITHUB_ENV
      - run: echo "NUID=$(id -u)" >> $GITHUB_ENV
      - name: pull images
        run: NUID=$NUID NGID=$NGID docker compose pull
      - name: tmate session
        uses: mxschmitt/action-tmate@v3
      #- run: docker compose run gatsby echo $UID
      #- run: docker compose run gatsby echo $GID
      #- name: gatsby ls
      #  run: docker compose run --rm gatsby ls -lhta
      #- name: gatsby id
      #  run: docker compose run --rm gatsby id
      #- name: host id
      #  run: id
      #- name: gatsby ls
      #  run: docker compose run --rm gatsby ls -lht
      - name: npm install
        run: NUID=$NUID NGID=$NGID docker compose run --rm gatsby npm ci
      - name: gatsby develop
        run: NUID=$NUID NGID=$NGID docker compose up --wait gatsby
      - name: run e2e tests
        run: NUID=$NUID NGID=$NGID docker compose up e2e_client
      - name: Upload image diff outputs
        uses: actions/upload-artifact@v3
        with:
          name: e2e image output directory
          path: gatsby/cypress/snapshots/
        if: failure()
 #lighthouse_audit:
 #  runs-on: ubuntu-latest
 #  steps:
 #    - name: checkout ${{ env.GITHUB_REF }}
 #      uses: actions/checkout@v3
 #    - uses: actions/setup-node@v3
 #      with:
 #        node-version: ${{ env.NODE_VERSION }}
 #    - env:
 #        CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
 #        CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
 #      run: cd gatsby && npm ci && npm run cy:install && npm run audit:ci
