name: cypress

permissions: read-all
on: [push]

env:
  NODE_VERSION: 22

jobs:
  e2e:
    runs-on: ubuntu-latest
    container: syntapynew/superformula_clone:latest
    steps:
      - name: checkout ${{ env.GITHUB_REF }}
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
        run: cd gatsby && npm ci && npm run cy:install && npm run e2e:ci
      - name: Upload image diff outputs
        uses: actions/upload-artifact@v3
        with:
          name: e2e image output directory
          path: gatsby/cypress/snapshots/
        if: failure()
  lighthouse_audit:
    runs-on: ubuntu-latest
    container: syntapynew/superformula_clone:latest
    steps:
      - name: checkout ${{ env.GITHUB_REF }}
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
        run: cd gatsby && npm ci && npm run cy:install && npm run audit:ci
