name: cypress

permissions: read-all
on: [push]

env:
  NODE_VERSION: 22

defaults:
  run:
    working-directory: ./gatsby

jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: syntapynew/superformula_clone:latest
      options: --user root
    steps:
      - name: checkout ${{ env.GITHUB_REF }}
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: install npm packages
        run: npm ci
      - name: install cypress
        run: npm run cy:install
      - name: run server in background
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
        run: npm run develop
      - name: wait
        run: sleep 2m
      - name: netstat -lt
        run: netstat -lt
      - name: Upload image diff outputs
        uses: actions/upload-artifact@v3
        with:
          name: e2e image output directory
          path: gatsby/cypress/snapshots/
        if: failure()
  #lighthouse_audit:
  # runs-on: ubuntu-latest
  # container:
  #   image: syntapynew/superformula_clone:latest
  #   options: --user root
  # steps:
  #   - name: checkout ${{ env.GITHUB_REF }}
  #     uses: actions/checkout@v3
  #   - uses: actions/setup-node@v3
  #     with:
  #       node-version: ${{ env.NODE_VERSION }}
  #   #- env:
  #   #    CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  #   #    CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
  #   #  run: npm ci && npm run cy:install && npm run audit:ci
