name: cypress

permissions: read-all
on: [push]

env:
  NODE_VERSION: 22
  DISPLAY: ""
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}

jobs:
  e2e:
    uses: ./.github/workflows/setup.yml
    runs-on: ubuntu-latest
    steps:
      - name: run e2e tests
        run: docker compose -f docker-compose.yml -f docker-compose.actions.yml run --rm e2e_client run e2e
      - name: Upload image diff outputs
        uses: actions/upload-artifact@v3
        with:
          name: e2e image output directory
          path: gatsby/cypress/snapshots/
        if: failure()
  lighthouse_audit:
    uses: ./.github/workflows/setup.yml
    runs-on: ubuntu-latest
    steps:
      - name: run audit tests
        run: docker compose -f docker-compose.yml -f docker-compose.actions.yml run --rm e2e_client run audit
      - name: Upload image diff outputs
        uses: actions/upload-artifact@v3
        with:
          name: e2e image output directory
          path: gatsby/cypress/snapshots/
        if: failure()
