name: cypress

permissions: read-all
on: [push]

env:
  NODE_VERSION: 22
  DISPLAY: ""

jobs:
  e2e:
    uses: ./.github/workflows/setup.yml
    secrets: inherit
    with:
      test-command: e2e
# lighthouse_audit:
#   uses: ./.github/workflows/setup.yml
#   secrets:
#     contentful_space_id: ${{ secrets.CONTENTFUL_SPACE_ID }}
#     contentful_access_token: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
#   with:
#     test-command: audit
