name: setup and install

env:
  NODE_VERSION: 22
  DISPLAY: ""

permissions: read-all

on:
  workflow_call:
    inputs:
      test-command:
        required: true
        type: string
    secrets:
      contentful_space_id:
        required: true
      contentful_access_token:
        required: true

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout ${{ env.GITHUB_REF }}
        uses: actions/checkout@v3
     #- name: tmate session
     #  uses: mxschmitt/action-tmate@v3
     #  env:
     #    CONTENTFUL_SPACE_ID: ${{secrets.contentful_space_id}}
     #    CONTENTFUL_ACCESS_TOKEN: ${{secrets.contentful_access_token}}
      - name: pull images
        run: docker compose pull
      - name: gatsby env
        env:
          CONTENTFUL_SPACE_ID: ${{secrets.contentful_space_id}}
          CONTENTFUL_ACCESS_TOKEN: ${{secrets.contentful_access_token}}
        run: docker compose -f docker-compose.yml -f docker-compose.actions.yml run --entrypoint env gatsby | grep -i contentful
      - name: gatsby - npm install
        run: docker compose run --rm -u root gatsby ci
      - name: cypress - npm install
        run: docker compose run --rm -u root e2e_client ci
      - name: run test
        run: docker compose -f docker-compose.yml -f docker-compose.actions.yml run --rm e2e_client run e2e ${{ inputs.test-command }}
      - name: Upload image diff outputs
        uses: actions/upload-artifact@v3
        with:
          name: e2e image output directory
          path: gatsby/cypress/snapshots/
        if: inputs.test-command == 'e2e' && failure()
