name: setup and install

env:
  NODE_VERSION: 22
  DISPLAY: ""

permissions: read-all

on:
  workflow_call:
    secrets:
      contentful_space_id:
        required: true
      contentful_access_token:
        required: true

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout ${{ env.GITHUB_REF }}
        uses: actions/checkout@v3
        #- name: set secrets
        #run: echo $(CONTENTFUL_SPACE_ID=${{secrets.contentful_space_id}}) >> GITHUB_ENV
        #- name: set secrets
        #run: echo $(CONTENTFUL_ACCESS_TOKEN=${{secrets.contentful_space_id}}) >> GITHUB_ENV
        #- name: show contentful space id
        #run: echo $CONTENTFUL_SPACE_ID
      - name: pull images
        run: docker compose pull
        #- name: tmate session
        #uses: mxschmitt/action-tmate@v3
      - name: gatsby - npm install
        run: docker compose run --rm -u root gatsby ci
      - name: cypress - npm install
        run: docker compose run --rm -u root e2e_client ci
      - name: gatsby develop
        run: docker compose -f docker-compose.yml -f docker-compose.actions.yml up --wait gatsby
        with:
          CONENTFUL_SPACE_ID: ${{secrets.contentful_space_id}}
          CONTENTFUL_ACCESS_TOKEN: ${{secrets.contentful_access_token}}
