name: docker

permissions: read-all
on: [push]

env:
  NODE_MODULES: "./gatsby/node_modules/"

jobs:
  ### CI TEST ###
  CI_Smoke_Test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout ${{ env.GITHUB_REF }}
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build CI container image
        run: ./bin/build-ci
      - name: npm run serve
        run: ./bin/run-ci

  ### DEV TEST ###
  Dev_Smoke_Test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout ${{ env.GITHUB_REF }}
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build dev container image
        run: ./bin/build-dev
      - name: install packages
        run: cd gatsby; npm install; cd ..
      - name: run dev server
        run: ./bin/run-dev
