name: docker

permissions: read-all
on: [push]
jobs:
  TestRunCi:
    runs-on: ubuntu-latest
    steps:
      - name: checkout ${{ env.GITHUB_REF }}
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build CI container image
        run: ./bin/build-ci
      - name: npm run serve
        run: ./bin/run-ci
      - name: wait for server
        uses: nev7n/wait_for_response@v1
        with:
          url: 'http://localhost:9000'
          responseCode: 200
          timeout: 60000
          interval: 1000
      - name: wget server
        run: wget --output-file=index_port_9000.html http://localhost:9000
          #- name: debug terminal
          #uses: mxschmitt/action-tmate@v3
      - name: check wget result
        run: |
          if [ ! -s index_port_9000.html ]
          then
            echo "port 9000 wget file should NOT be empty"
            exit 1
          fi
      - name: rm wget result
        run: rm -f index_port_9000.html index.html
