name: docker

permissions: read-all
on: [push]

jobs:
  TestRunCi:
    runs-on: ubuntu-latest
    env:
      SERVER: 'http://localhost:9000'
      WGET_FILE: index_port_9000.html
    steps:
      - name: checkout ${{ env.GITHUB_REF }}
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build CI container image
        run: ./bin/build-ci
      - name: npm run serve
        run: ./bin/run-ci
      - name: sleep + curl -I
        run: sleep 40; curl -I 
      - name: wait for server
        uses: nev7n/wait_for_response@v1
        with:
          url: $SERVER_CI
          responseCode: 200
          timeout: 60000
          interval: 1000
      - name: wget server
        run: wget --output-file=$WGET_FILE $SERVER
          #- name: debug terminal
          #uses: mxschmitt/action-tmate@v3
      - name: check wget result
        run: |
          if [ ! -s $SERVER ]
          then
            echo "port 9000 wget file should NOT be empty"
            exit 1
          fi
      - name: rm wget result
        run: rm -f $WGET_FILE index.html

  TestRunDev:
    runs-on: ubuntu-latest
    env:
      SERVER: 'http://localhost:8000'
      WGET_FILE: index_port_8000.html
    steps:
      - name: checkout ${{ env.GITHUB_REF }}
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build dev container image
        run: ./bin/build-dev
      - name: check no node_modules
        run: |
          if [ -d "./node_modules" ]
          then
            echo "node_modules exists when it shouldn't"
            exit 1
          fi
          #- name: debug terminal
          #uses: mxschmitt/action-tmate@v3
      - name: install packages
        run: cd gatsby; npm install
      - name: check node_modules exists
        run: |
          if [ ! -d "./node_modules" ]
          then
            echo "node_modules *should* exist!"
            exit 1
          fi
      - name: run dev server
        run: ./bin/run-dev
      - name: sleep + curl -I
        run: sleep 40; curl -I $SERVER
      - name: wait
        uses: nev7n/wait_for_response@v1
        with:
          url: $SERVER
          responseCode: 200
          timeout: 180000
          interval: 2000
      - name: wget
        run: wget --output-file=$WGET_FILE $SERVER
      - name: check wget result
        run: |
          if [ ! -s $WGET_FILE ]
          then
            echo "port 8000 wget file should NOT be empty"
            exit 1
          fi
      - name: rm wget result
        run: rm -f $WGET_FILE index.html
