name: docker

permissions: read-all
on: [push]
jobs:
  TestRunDev:
    runs-on: ubuntu-latest
    steps:
      - name: checkout ${{ env.GITHUB_REF }}
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build dev container image
        run: ./bin/build-dev
      - name: check no node_modules
        run: |
          if [ -d "./node_modules" ]
          then
            echo "node_modules exists when it shouldn't"
            exit 1
          fi
      - name: install packages
        run: npm install
      - name: check node_modules exists
        run: |
          if [ ! -d "./node_modules" ]
          then
            echo "node_modules *should* exist!"
            exit 1
          fi
      - name: run dev server
        run: ./bin/run-dev
      - name: sleep + curl -I
        run: sleep 120; curl -I http://lcalhost:8000
      - name: wait
        uses: nev7n/wait_for_response@v1
        with:
          url: 'http://localhost:8000'
          responseCode: 200
          timeout: 180000
          interval: 2000
      - name: wget
        run: wget --output-file=index_port_8000.html http://localhost:8000
      - name: check wget result
        run: |
          if [ ! -s index_port_8000.html ]
          then
            echo "port 8000 wget file should NOT be empty"
            exit 1
          fi
      - name: rm wget result
        run: rm -f index_port_8000.html index.html
          #- name: ifconfig
          #run: ifconfig
          #- name: ping localhost
          #run: ping -c 5 -4 localhost
          #- name: ping server
          #run: ping -c 5 -4 localhost:9000
          #      - name: ping server
          #        uses: BerniWittmann/background-server-action@v1
          #        with:
          #command: ping -c 10 http://localhost:8000
          #          command: ifconfig
          #          start: ./bin/run-ci
          #          wait-on: 'http://localhost:8000'
            #      - name: run container
            #        run: ./bin/run-ci
            #      - name: ping container
            #        run: ping -c 5 localhost:8000
