name: docker

permissions: read-all
on: [push]

env:
  NODE_MODULES: "./gatsby/node_modules/"

jobs:
  TestRunCi:
    runs-on: ubuntu-latest
    env:
      SERVER: http://localhost:9000
      WGET_FILE: index_port_9000.html
    steps:
      - name: checkout ${{ env.GITHUB_REF }}
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build CI container image
        run: ./bin/build-ci
      - name: npm run serve
        run: ./bin/run-ci
          #- name: debug terminal
          #uses: mxschmitt/action-tmate@v3
      - name: wget server
        run: wget --output-file=$WGET_FILE $SERVER
      - name: check wget result
        run: |
          if [ ! -s $WGET_FILE ]
          then
            echo "port 9000 wget file should NOT be empty"
            exit 1
          fi
      - name: rm wget result
        run: rm -f $WGET_FILE index.html


  ### DEV TEST ###

  TestRunDev:
    runs-on: ubuntu-latest
    env:
      SERVER: http://localhost:8000
      WGET_FILE: index_port_8000.html
    steps:
      - name: checkout ${{ env.GITHUB_REF }}
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build dev container image
        run: ./bin/build-dev
      - name: check no node_modules
        run: |
          if [ -d $NODE_MODULES ]
          then
            echo "node_modules exists when it shouldn't"
            exit 1
          fi
      - name: debug terminal
        uses: mxschmitt/action-tmate@v3
      - name: install packages
        run: cd gatsby; npm install
      - name: check node_modules exists
        run: |
          if [ ! -d $NODE_MODULES ]
          then
            echo "node_modules *should* exist!"
            exit 1
          fi
      - name: run dev server
        run: ./bin/run-dev
      - name: wget
        run: wget --output-file=$WGET_FILE $SERVER
      - name: check wget result
        run: |
          if [ ! -s $WGET_FILE ]
          then
            echo "port 8000 wget file should NOT be empty"
            exit 1
          fi
      - name: rm wget result
        run: rm -f $WGET_FILE index.html
