name: docker

permissions: read-all
on: [push]
inputs:
  varFilePath:
    description: 'variables'
    required: true
    default: ./.github/variables.env
jobs:
  TestRunCi:
    runs-on: ubuntu-latest
    steps:
      - name: load environment variables
        uses: srini-hv/load-env-vars
        with:
          file-path: "./.github/variables.env"
          delimiter: "="
      - name: checkout ${{ env.GITHUB_REF }}
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build CI container image
        run: ./bin/build-ci
      - name: npm run serve
        run: ./bin/run-ci
      - name: sleep + curl -I
        run: sleep 60; curl -I http://localhost:9000
      - name: wait for server
        uses: nev7n/wait_for_response@v1
        with:
          url: $SERVER_CI
          responseCode: 200
          timeout: 60000
          interval: 1000
      - name: wget server
        run: wget --output-file=$WGET_FILE_CI http://localhost:9000
          #- name: debug terminal
          #uses: mxschmitt/action-tmate@v3
      - name: check wget result
        run: |
          if [ ! -s index_port_9000.html ]
          then
            echo "port 9000 wget file should NOT be empty"
            exit 1
          fi
      - name: rm wget result
        run: rm -f index_port_9000.html index.html
